fix crash when XCURSOR_SIZE environment variable is set incorrectly
hyprwm/hyprpaper pull request #24
Opened 2022-12-06 06:16 UTC by vilari-mickopf

Fix #23

2022-12-13 20:19 UTC, vaxerski requested changes

2022-12-13 20:19 UTC, vaxerski commented on src/Hyprpaper.cpp
> +        if (getenv("XCURSOR_SIZE") != NULL) {
this is very C, and it ends with you calling getenv twice.

if(const auto CURSORSIZENV = getenv(..); CURSORSIZEENV)

2022-12-13 20:19 UTC, vaxerski commented on src/Hyprpaper.cpp
> +            XCURSOR_SIZE = strtol(getenv("XCURSOR_SIZE"), &endptr, 10);
again, very C.

try {
   xcursor_size = std::stoi(cursorsizeenv);
} catch (...) {
 whatever err handling
}

2022-12-13 20:19 UTC, vaxerski commented
stg I am retarded I added the comments and didnt hit submit :skull:

2022-12-18 21:29 UTC, vilari-mickopf commented
Haven't done c++ in a while, hope it's better now.

2022-12-18 22:54 UTC, vaxerski commented
thanks!

2022-12-18 22:54 UTC, vaxerski approved these changes

2022-12-18 22:54 UTC, merged